# Generated by Django 6.0.3 on 2026-03-17 12:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_group_members', models.IntegerField(default=50, help_text='Группы с бо́льшим числом участников игнорируются', verbose_name='Макс. участников в группе')),
                ('download_audio', models.BooleanField(default=False, verbose_name='Скачивать аудио')),
                ('download_documents', models.BooleanField(default=False, verbose_name='Скачивать документы')),
                ('max_file_size_mb', models.IntegerField(default=50, help_text='Файлы больше этого размера не скачиваются', verbose_name='Макс. размер файла (МБ)')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='Telegram ID сообщения')),
                ('date', models.DateTimeField(verbose_name='Дата отправки')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('video_note', 'Кружок'), ('sticker', 'Стикер'), ('gif', 'GIF'), ('document', 'Документ'), ('poll', 'Опрос'), ('location', 'Геолокация'), ('contact', 'Контакт'), ('unknown', 'Неизвестно')], default='text', max_length=20, verbose_name='Тип')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('media_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('sticker_emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='Эмодзи стикера')),
                ('sticker_set', models.CharField(blank=True, max_length=255, null=True, verbose_name='Набор стикеров')),
                ('audio_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название трека')),
                ('audio_artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнитель')),
                ('poll_question', models.TextField(blank=True, null=True, verbose_name='Вопрос опроса')),
                ('poll_options', models.JSONField(blank=True, null=True, verbose_name='Варианты ответа')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя контакта')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон контакта')),
                ('contact_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID контакта')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='Транскрипция')),
                ('transcription_pending', models.BooleanField(default=False, verbose_name='Транскрипция в процессе')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Пересланное')),
                ('forward_from_id', models.BigIntegerField(blank=True, null=True, verbose_name='Переслано от (ID)')),
                ('forward_from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Переслано от (имя)')),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Ответ на сообщение ID')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Отредактировано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('is_self', models.BooleanField(default=False, verbose_name='Это я')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='MessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст до редактирования')),
                ('edited_at', models.DateTimeField(verbose_name='Время редактирования')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='archive.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'История правок',
                'verbose_name_plural': 'История правок',
                'ordering': ['edited_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID чата')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('chat_type', models.CharField(choices=[('private', 'Личная переписка'), ('group', 'Группа'), ('bot', 'Бот')], max_length=20, verbose_name='Тип')),
                ('member_count', models.IntegerField(blank=True, null=True, verbose_name='Участников')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'indexes': [models.Index(fields=['-updated_at'], name='archive_tel_updated_0f7fd0_idx')],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archive.telegramchat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='archive.telegramuser', verbose_name='Отправитель'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-date'], name='idx_message_chat_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'message_id'], name='idx_message_chat_msgid'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('transcription_pending', True)), fields=['transcription_pending'], name='idx_message_transcription_pending'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_message_search_vector'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('chat', 'message_id'), name='unique_message_in_chat'),
        ),
    ]
