# Generated by Django 6.0.3 on 2026-03-17 12:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_group_members', models.IntegerField(default=50, help_text='Groups with more members are ignored', verbose_name='Max group members')),
                ('download_audio', models.BooleanField(default=False, verbose_name='Download audio')),
                ('download_documents', models.BooleanField(default=False, verbose_name='Download documents')),
                ('max_file_size_mb', models.IntegerField(default=50, help_text='Files larger than this size are not downloaded', verbose_name='Max file size (MB)')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='Telegram message ID')),
                ('date', models.DateTimeField(verbose_name='Sent at')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice'), ('video_note', 'Video note'), ('sticker', 'Sticker'), ('gif', 'GIF'), ('document', 'Document'), ('poll', 'Poll'), ('location', 'Location'), ('contact', 'Contact'), ('unknown', 'Unknown')], default='text', max_length=20, verbose_name='Type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('media_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='File path')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File name')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File size (bytes)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('sticker_emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sticker emoji')),
                ('sticker_set', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sticker set')),
                ('audio_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Track title')),
                ('audio_artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artist')),
                ('poll_question', models.TextField(blank=True, null=True, verbose_name='Poll question')),
                ('poll_options', models.JSONField(blank=True, null=True, verbose_name='Answer options')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact phone')),
                ('contact_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram contact ID')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='Transcription')),
                ('transcription_pending', models.BooleanField(default=False, verbose_name='Transcription in progress')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Forwarded')),
                ('forward_from_id', models.BigIntegerField(blank=True, null=True, verbose_name='Forwarded from (ID)')),
                ('forward_from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forwarded from (name)')),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Reply to message ID')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('is_self', models.BooleanField(default=False, verbose_name='This is me')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
        migrations.CreateModel(
            name='MessageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text before edit')),
                ('edited_at', models.DateTimeField(verbose_name='Edit time')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='archive.message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Edit history',
                'verbose_name_plural': 'Edit history',
                'ordering': ['edited_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('chat_type', models.CharField(choices=[('private', 'Private chat'), ('group', 'Group'), ('bot', 'Bot')], max_length=20, verbose_name='Type')),
                ('member_count', models.IntegerField(blank=True, null=True, verbose_name='Members')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'indexes': [models.Index(fields=['-updated_at'], name='archive_tel_updated_0f7fd0_idx')],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='archive.telegramchat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='archive.telegramuser', verbose_name='Sender'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-date'], name='idx_message_chat_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'message_id'], name='idx_message_chat_msgid'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('transcription_pending', True)), fields=['transcription_pending'], name='idx_message_transcription_pending'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_message_search_vector'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('chat', 'message_id'), name='unique_message_in_chat'),
        ),
    ]
