# Generated by Django 6.0.3 on 2026-03-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='idx_msg_transcribe_pending',
            old_name='idx_message_transcription_pending',
        ),
    ]
